# Generated by Django 3.2.5 on 2021-07-28 05:13

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_auto_20210728_1404'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_date',
            field=models.DateField(default=datetime.datetime(2021, 7, 28, 5, 13, 54, 204416, tzinfo=utc), verbose_name='受注日'),
        ),
        migrations.AlterField(
            model_name='order',
            name='section',
            field=models.CharField(blank=True, choices=[(None, '---------'), ('1F', '1F'), ('1FA', '1FA'), ('1J', '1J'), ('1JA', '1JA'), ('1P', '1P'), ('1PA', '1PA'), ('1S', '1S'), ('2F', '2F'), ('2FA', '2FA'), ('2J', '2J'), ('2JA', '2JA'), ('2P', '2P'), ('2PA', '2PA')], default=None, max_length=3, null=True, verbose_name='摘要'),
        ),
        migrations.AlterField(
            model_name='orderwork',
            name='date',
            field=models.DateField(default=datetime.datetime(2021, 7, 28, 5, 13, 54, 205009, tzinfo=utc), verbose_name='日付'),
        ),
    ]
