# Generated by Django 3.2.5 on 2021-07-30 06:13

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_auto_20210728_1413'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='lot_number',
            field=models.CharField(max_length=20, verbose_name='Lot No.'),
        ),
        migrations.AlterField(
            model_name='order',
            name='name',
            field=models.CharField(max_length=100, verbose_name='品名'),
        ),
        migrations.AlterField(
            model_name='order',
            name='order_date',
            field=models.DateField(default=datetime.datetime(2021, 7, 30, 6, 13, 35, 702604, tzinfo=utc), verbose_name='受注日'),
        ),
        migrations.AlterField(
            model_name='order',
            name='work_content',
            field=models.CharField(max_length=50, verbose_name='作業内容'),
        ),
        migrations.AlterField(
            model_name='orderwork',
            name='date',
            field=models.DateField(default=datetime.datetime(2021, 7, 30, 6, 13, 35, 703306, tzinfo=utc), verbose_name='日付'),
        ),
    ]
